### ISSUE TITLE
Cannot reload while MuleQueue is active

### ISSUE THREAD

**Issue by RealmMasterInsaneBlaze** [jakcodex/muledump#128]
Whenever I try to reload my other accounts or something I get 

"Cannot reload while MuleQueue is active"

and It doesn't load my other mules or refresh

**Comment by jakcodex** [comment]
MuleQueue v1 has a lot of issues and this is one of them. 

MuleQueue v2 is actually the primary focus of Muledump v9.1. You can see it in action on Muledump Preview here: https://jakcodex.github.io/muledump-preview/muledump.html

Let me know what you think of it!

**Comment by RealmMasterInsaneBlaze** [comment]
Wow! This v2 looks awesome! Thanks! @jakcodex

**Comment by RealmMasterInsaneBlaze** [comment]
Just one issue, when I reload the page it doesn't really save the accounts that I reloaded @jakcodex

**Comment by jakcodex** [comment]
I'm not sure what you mean? Mind joining the Discord so we can have a realtime chat about it?

**Comment by RealmMasterInsaneBlaze** [comment]
@jakcodex Sure! What's your discord?

**Comment by jakcodex** [comment]
Jaki#7996

We have an official Discord you too you know - https://discord.gg/JFS5fqW
