### ISSUE TITLE
Muledump not showing all item totals

### ISSUE THREAD

**Issue by vinstaal0** [jakcodex/muledump#13]
In this picture: https://gyazo.com/1f1908c3785178159068febe94e6f1ec

You can see that some of my charachter have items, that do not show up in the item totals. This happend after I was toggeling some settings, but while trying to do that again to fix it, it stays the same

**Comment by jakcodex** [comment]
This is likely due to existing code in totals.js. I will check it out.

**Comment by RotMGBotkiller** [comment]
Most likely, vinstaal0 toggled the Fame Bonus Filter option, making lower fame items not show up in the totals. It looks like the fame bonus was set to >5%. Not a bug.

Here's an image to show what option I mean: http://i.imgur.com/zjwAYXO.png

**Comment by vinstaal0** [comment]
Ow rip, my bad

**Comment by jakcodex** [comment]
Thanks Botkiller.
