### ISSUE TITLE
Adjustable interval in between account reloads

### ISSUE THREAD

**Issue by Spruudel** [jakcodex/muledump#142]
Because reload time when having lots of mules is unbearable, being able to manually set the delay in between requests would be neat.
With a VPN you can easily avoid rate limiting, so that's not a problem.

**Comment by jakcodex** [comment]
Setup > Settings > Account Load Delay in Seconds

It defaults to automatic (0), but you can change it to manual and set it between 1 and 40 seconds.

**Comment by Spruudel** [comment]
Oh, well. Did not notice it...
