### ISSUE TITLE
open MuleQueue Manager on "x Tasks Running" panel

### ISSUE THREAD

**Issue by Spruudel** [jakcodex/muledump#151]
I often click on the "x Tasks Running" button/link, instead of the actual "MuleQueue" button and find it rather unnatural/annoying, to not be able to open it that way.

**Comment by jakcodex** [comment]
I had this same thought while I was working on it and had decided to try it the way it is now. I'll see about this change. Expect to see it in preview soon. Will update this issue when it is so you can feel it out :)
