### ISSUE TITLE
Accounts manager broken

### ISSUE THREAD

**Issue by marksg07** [jakcodex/muledump#185]
When I open the accounts manager window, after a second, all the account emails and passwords on the first page become my main's email and password. If I save after this, all the accounts on the first page are deleted. This is preventing me from adding a new account and changing old accounts' info.

**Comment by jakcodex** [comment]
This is likely an issue local to you with an odd cause. Let's see if we can get any debug data for this.

Can you load Muledump and then in your browser hit F12 then click on Console? Once there, repeat the steps above and see if any errors are produced.

Can you tell me your browser version? For Chrome you can go to the url `about:chrome`.

**Comment by marksg07** [comment]
No errors when I open the accounts tab, but when I close it after experiencing the bug, I get the following warning/error:
`content.js:16455 reportFormCapture failed TypeError: Cannot read property 'length' of null
    at generateXPath (content.js:16543)
    at Object.reportFormCapture (content.js:16650)
    at Object.reportFormCapture (content.js:16452)
    at Avast.Namespace.define.InputCapturer.Avast.Class.mix.Avast.Class.define._form.processDraft (content.js:19222)
    at Avast.Namespace.define.InputCapturer.Avast.Class.mix.Avast.Class.define._form.onFormRemoved (content.js:19349)
    at Avast.Class.derive._type.<anonymous> (content.js:823)`
multiple times. I get the error once for each account that is overwritten. For example, on the first page, I get 4 errors because the first account is the one that's overwriting everything else. On the second page, I get 5. Also, I noticed the multiple "Avast"s in the error, and I turned off all the web-related components of Avast. After a restart, the same error persists. What steps should I take to resolve this?

**Comment by marksg07** [comment]
Figured it out. Avast passwords was the problem. I'm guessing it was automatically detecting every field in the accounts manager as the same, and replacing them all with the saved email and password.

**Comment by jakcodex** [comment]
Password managers have been a pain. I added a feature to block them, but it turns out most simply ignore that HTML setting... oi. Glad you figured it out!
