### ISSUE TITLE
One-click Login Not Working? Virus?

### ISSUE THREAD

**Issue by aaron1259** [jakcodex/muledump#198]
My one-click login doesn't seem to work, it did show as a false positive on windows defender which I tried to restore, would this causing it not to work?

I'm using the default au3

**Comment by jakcodex** [comment]
Windows Defender is giving a false positive for one click login. Not sure why it is triggering tho.

https://www.virustotal.com/#/url/50e70f6b777d2192d789f2efcc2d1dc73fc6fc0850a4be8a7a2e31ae6b8a9256/detection

By chance, are you the guy I helped with the same issue via Discord?
