### ISSUE TITLE
some items in totals aren't actually in an account

### ISSUE THREAD

**Issue by 09morbab** [jakcodex/muledump#199]
as the title says there are items that are in my totals but not in an account.
currently i have a single taco that i don't have (if i click on it i get no accounts come up)
it seems a bit random but removing all accounts and putting them in again doesn't help 
I've had this before with various other items with totals leading me to think i have more than i have
(its not that i haven't refreshed the accounts, filter by item comes up with nothing)

**Comment by jakcodex** [comment]
Can you verify which version of Muledump you are using? Also, what are your options and totals filters set to?

**Comment by 09morbab** [comment]
im using 9.2.0
and 
https://imgur.com/a/r3CUV9H

**Comment by 09morbab** [comment]
no ghost items there as far as i can see

**Comment by 09morbab** [comment]
nope i found one and epic quest chest this time (only when i have global on tho( its not in a gift chest))

**Comment by jakcodex** [comment]
Muledump v9.3 has been published. Can you update and check again? Thank you.
