### ISSUE TITLE
Create 300 second timeout upon rate limit error?

### ISSUE THREAD

**Issue by mouselifter** [jakcodex/muledump#2]
Would solve having multiple folders if you have many accounts.

**Comment by jakcodex** [comment]
Heya,

This has been rolled into the current testing branch (see: https://github.com/jakcodex/muledump/tree/vaultorder1).

When rate limiting is detected, the system now marks a time 5 minutes in the future and stores it to localStorage. Until the time expires, all attempts to reload character data are blocked. The system will serve cached account data wherever possible in the meantime.

I've also added the ability to cancel loading of accounts waiting in the queue. For example, if you're loading thru a list of 50 accounts you can now cancel at any point. When a queue is active, the 'reload all' button changes to 'cancel reload'.

Changing options was triggering account reloads. This could cause rate limiting rather quickly with large accounts.js files. This now reloads from cache only.

Check it out. Tell me what you think.

**Comment by jakcodex** [comment]
This has been released in v0.7.5.
