### ISSUE TITLE
Use for mobile?

### ISSUE THREAD

**Issue by xqzba** [jakcodex/muledump#220]
How would I use this for mobile (Android phone). I would like to use this on my phone when I go on trips so I do not miss any daily rewards.

**Comment by jakcodex** [comment]
Wow, sorry for the delayed response here. I missed seeing it. 

There is no official way to do this presently. You would need a browser that doesn't enforce CORS restrictions to accomplish this. I am not aware of such options at this time that would work universally.

Maybe in the future? If you find something that works let me know.
