### ISSUE TITLE
Chrome Online Version One Click Login No Longer Working

### ISSUE THREAD

**Issue by 55645nato** [jakcodex/muledump#223]
One click login takes me to ROTMG but does not log in. I have been using one click login on chrome for some time before this with no issue. I tried reinstalling chrome, the extension, and the autoit script. Firefox still worked and using local muledump on chrome still worked. I plan to just use the local version going forward so I don't have to wait for a fix, but I thought I would post this in case anyone else is having the same issue.

Thanks for putting the time in to make such a great tool. I couldn't live without it.

**Comment by jakcodex** [comment]
Hiya,

Just to confirm, did you make sure you tried reinstalling the OCL script from version 9.3.1? 

Typically in Chrome when it doesn't work there's a path error where OCL is no longer able to access the location of the SOL file. In this case, switching to Flash Projector is recommended until a longterm fix can be implemented.

-Jaki

**Comment by 55645nato** [comment]
🤦‍♂️  It now magically works today. Probably restarting my computer would have fixed the problem. Thanks for following up with me and have a great day!
