### ISSUE TITLE
Removing account from accounts.js doesn't work?

### ISSUE THREAD

**Issue by KiloChaser** [jakcodex/muledump#233]
I tried removing an account I don't use anymore from the accounts.js file but it still shows up and reloads whenever I reload my accounts. Did you change the way this works or is there another way?

**Comment by jakcodex** [comment]
Did you happen to go through the SetupTools install?

Check by clicking 'Setup' in the top menu. If you're greeted with "Muledump Manager" then click "Accounts" and remove the account there instead.
