### ISSUE TITLE
text item count of frame

### ISSUE THREAD

**Issue by TadusPro** [jakcodex/muledump#265]
Total amout of item number is out of frame when more then 10 000, or 10k. My suggestion to fix this is to make it say 10K when it hits 10 000
![image](https://user-images.githubusercontent.com/22742194/53455403-a141eb00-3a2a-11e9-8897-ab12f107d148.png)

**Comment by jakcodex** [comment]
![image](https://user-images.githubusercontent.com/28816370/54415591-b07f9480-46ca-11e9-9df5-ea6d879dbfab.png)

Have to keep it limited to 1 decimal place; otherwise, it jumps its boundaries.

**Comment by TadusPro** [comment]
Awesome!! :DD

**Comment by jakcodex** [comment]
Just adding some notes for the record here :)

Tooltip is also updated now to display the value for shortened numbers.

![image](https://user-images.githubusercontent.com/28816370/54486772-04b97e80-485b-11e9-9aa0-bcfb7f1aa7d7.png)

Item tooltip had all floats removed and replaced with flex boxes.

**Comment by jakcodex** [comment]
Released in Muledump v9.6.
