### ISSUE TITLE
steam credentials not saving. Am I doing something wrong?

### ISSUE THREAD

**Issue by macks2008** [jakcodex/muledump#295]
I followed the set up for steam users to the letter, even installing fiddler's root certificate authority as is apparently required now for the "decrypt HTTPS traffic" option to work, but when I try to save the GUID and secret in SetupTools, it either clears the line for that account (if I click "Add New Account" so I can add another) or tells me "no valid accounts located!" if I try to save. Despite this, the ID and secret look valid, just like the ones in the setup guide, so I don't think I did something wrong with that... Unless I did?

- Possibly worth noting, I downloaded the application as a clone of my fork of the repository, so if it's a simple fix to the application (as opposed to something complicated or I'm doing wrong with setup) I could probably just patch it myself and submit a PR relatively easily... I just don't know shit about JavaScript and don't want to attempt a fix without guidance, especially not without the context of knowing how this thing works in the first place.

**Comment by jakcodex** [comment]
Resolved in Discord chat.

In a nutshell: When you copy steamworks credentials from Fiddler, it might be a good idea to paste it into Notepad and copy it back out to make sure no invisible chars get copied with the guid.

**Comment by macks2008** [comment]
Oh, you closed it. Thanks. Was about to do that myself :-)
