### ISSUE TITLE
Steam Information Issues

### ISSUE THREAD

**Issue by Scotty7298** [jakcodex/muledump#296]
Hello. I am able to start the game with Steam normally. However, when I have Fiddler running to help me grab my account info, it gives me a notification that the certificate isn't trusted. Regardless of if I pick "yes" or "no" to proceed, the steam player gives me "version loading error, retrying" and I never reach the main menu. How should I proceed?

**Comment by jakcodex** [comment]
Sorry for the no reply here. Discord has ultimately been the best choice for user support.
