### ISSUE TITLE
Being able to see the available Quests for each mule/all mules

### ISSUE THREAD

**Issue by RedKage** [jakcodex/muledump#300]
Hey there,

As each user has their own quests set, there is actually a lot of stuff that can be unlocked with many mules. Problem is to login with each mule and go to the quest screen would take ages with lots of mules.

If we could see, either an unified view with all the available quests, or for each mule their quest sets, that'd speed things up and we could easily target all the quests across the accounts that we can fulfill!

Not sure if there is an API for the quest list though

**Comment by RedKage** [comment]
Well, it's all in AS3 events it seems. There's no backend API for this so ...
That's not possible. Yet.

This guy https://github.com/Zeroeh/RotMG-Appspot seems to maintain a list of found APIs.
Maybe in the future Deca will expose more stuff with these regular APIs and less with AS3 events. 
Maybe in this case we could call some new APIs
But not now anyway.

**Comment by jakcodex** [comment]
Deca recently announced development of a 3rd party API for apps like Muledump to use going forward. Hopefully a lot more information will be exposed and made available :)
