### ISSUE TITLE
Vault showing as empty

### ISSUE THREAD

**Issue by RyanLMc** [jakcodex/muledump#302]
Vault space is beiong shown as empty despite being full i have reloaded all accounts and tried everything i can think if

**Comment by Quandrant** [comment]
I also have this blank vault issue. Paging @jakcodex for insight on this bug (assuming they have it).

**Comment by TheScootz** [comment]
I was having this issue yesterday as well, but as of today it seems to have fixed itself?

**Comment by Quandrant** [comment]
@TheScootz Glad to know it works now. I'll check later today just to make sure.

@RyanLMc, [here's an explanation on reddit (that is in turn copied from the Discord) on why Muledump is/was not working.](https://www.reddit.com/r/RotMG/comments/gnuet6/is_anybody_elses_muledump_completely_broken/frc08a7/)

**Comment by jakcodex** [comment]
Yikes this is a late reply. To summarize, this was a bug on Deca's side from a change they had made and subsequently fixed.
