### ISSUE TITLE
I added a new renders + constants if you want :)

### ISSUE THREAD

**Issue by wawawawawawawa** [jakcodex/muledump#48]

**Comment by jakcodex** [comment]
If only we could do pull requests for just these files! Thank you, I'll push it to master and Muledump Online tonight as v0.8.1-7.

**Comment by jakcodex** [comment]
You're missing this:

./Pets.xml:   <Object type="0x4cba" id="Moon Bunny Pet Stone">

**Comment by jakcodex** [comment]
I've pushed this to Muledump Online, finally. It'll be included in the next actual release of Muledump Local.

I look forward to the next update with Moon Bunny and the Halloween updates :)

Thanks!
