### ISSUE TITLE
Options menu bugged on firefox

### ISSUE THREAD

**Issue by jvorob** [jakcodex/muledump#49]
When looking at the options menu, the checkboxes and corresponding text aren't aligned, and it compounds to the point that clicking the text for backpacks toggles the checkbox 3 rows down which is next to stats.

It seems the checkboxes/text aren't staying in their divs.

Adding the following css rule seems to fix it

    .menu div { overflow: hidden; }

I'm on ubuntu, running muledump in firefox.

**Comment by jakcodex** [comment]
I will look into this. The next major update won't roll out until I finish Groups Manager, so I'll slate this to be included with that.

**Comment by jakcodex** [comment]
Can you check in Muledump Preview if this issue is resolved for you? I was unable to replicate it; however, others have reported it since this issue was opened. 

https://jakcodex.github.io/muledump-preview/muledump.html

**Comment by jvorob** [comment]
Still seems to be happening.

![image](https://user-images.githubusercontent.com/1192632/32564752-31f017f4-c483-11e7-9360-48e5cd2b9f0d.png)

This seems to have an explanation of the issue
https://stackoverflow.com/questions/2062258/floating-elements-within-a-div-floats-outside-of-div-why

**Comment by jakcodex** [comment]
I have overflow:hidden set on the span.menu but it isn't helping you. There is a blank div between the span and the actual options. Could you download master from muledump-preview, extract it, update lib/dump.js, and try again locally?

Add to lib/dump.js --

.menu:not(.setuptools) > div { overflow: hidden; }

If that doesn't work, you can try this to apply it to all menu children divs:

.menu:not(.setuptools) div { overflow: hidden; }

**Comment by jakcodex** [comment]
Another user who reported this issue says it is fixed for them in Firefox on Muledump Preview. Moving to ready.

**Comment by jvorob** [comment]
Ack, sorry just got around to checking it. Just confirming:

The first variation only fixes the top-level options, the radio buttons are still misaligned (but is much better since it doesn't accumulate over the whole menu). The second option (applied to all descendant divs) fixes the issue fully.

Also, my checkboxes look like that because I'm running ubuntu; I haven't set up any custom things for that I don't think.

**Comment by jakcodex** [comment]
Okay. I suspect your buttons are contributing. I'll try and widen that overflow: hide option across the menu and we can try again. Will be up tonight on preview.

**Comment by jakcodex** [comment]
I added overflow:hidden to the label but I don't think that's going to help. Looking at the menu structure and the hidden on menu>div should have done the job.

If the css modifications changed the menu look for you can you provide an updated screenshot?

**Comment by jvorob** [comment]
Yep, the 0.8.2-0 branch has it working correctly for me! Good stuff. (I think I was still looking at master the previous time I checked ._. )


![image](https://user-images.githubusercontent.com/1192632/33033667-34fbc5b4-cdf3-11e7-943a-b2538062eed7.png)

**Comment by jakcodex** [comment]
Oh cool. Glad to hear it! Marking as closed :)
