### ISSUE TITLE
CANNOT ENTER TO ROTMG AFTER SETTING MULEDUMP

### ISSUE THREAD

**Issue by Jilculiaox** [jakcodex/muledump#72]
hey guys i was trying to setup muledump stuff and when i did it, some error starter and after that i cannot enter the game from nowhere.. please help, when i apply the flash player projector it says loading for ever.. please help not even in google chrome can play, not even steam is working

**Comment by jakcodex** [comment]
Does Muledump produce an error then too? The error you describe sounds like something Deca did on their end. 

Does Muledump mention rate limiting or any errors of any kind?

Nothing in the Muledump setup itself can break your access to ROTMG.
