### ISSUE TITLE
Additional stats can cause mp block to be misaligned

### ISSUE THREAD

**Issue by jakcodex** [jakcodex/muledump#85]
![image](https://user-images.githubusercontent.com/28816370/33582274-0b68b0c2-d91a-11e7-9ed7-61b9f8bc518c.png)

**Comment by Curlip** [comment]
For those interested. I believe the fix was to change the MP Block to `float: left;`. This appears to have been fixed in preview already. This is one of these little annoying things, that I am happy to see fixed.

**Comment by jakcodex** [comment]
Released in v9.0.0
